// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIod1vcilEH7vz86sT5AlXsnduuOrAv98',
    appId: '1:668255069444:web:f684a9d834990e0a15dc51',
    messagingSenderId: '668255069444',
    projectId: 'immocrowd-49e21',
    authDomain: 'immocrowd-49e21.firebaseapp.com',
    databaseURL: 'https://immocrowd-49e21-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'immocrowd-49e21.appspot.com',
    measurementId: 'G-T9K9Y1ZGF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIMeYtJAAaWK9zREKDrP91Itawwp2T8NI',
    appId: '1:668255069444:android:ec2b2bee454e3d2f15dc51',
    messagingSenderId: '668255069444',
    projectId: 'immocrowd-49e21',
    databaseURL: 'https://immocrowd-49e21-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'immocrowd-49e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbYoSiqUYVvpQcuDWgDYwLSpvjsBrWE7k',
    appId: '1:668255069444:ios:cab0097f9f78017315dc51',
    messagingSenderId: '668255069444',
    projectId: 'immocrowd-49e21',
    databaseURL: 'https://immocrowd-49e21-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'immocrowd-49e21.appspot.com',
    iosClientId: '668255069444-buvi3bvjj3pmuf3nulss3i128qe269kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.immocrowd',
  );
}
