// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWlJBwd_ldJOPxHh6QOc6oVxjcaQJeRv8',
    appId: '1:977443506924:web:009766f6a0f6bf6aff33c9',
    messagingSenderId: '977443506924',
    projectId: 'coogen-9b081',
    authDomain: 'coogen-9b081.firebaseapp.com',
    databaseURL: 'https://coogen-9b081-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coogen-9b081.appspot.com',
    measurementId: 'G-7E6KHC444V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Xff_mKprYFECFLfnbRT6eyxT6TgRinQ',
    appId: '1:977443506924:android:b0987766763547faff33c9',
    messagingSenderId: '977443506924',
    projectId: 'coogen-9b081',
    databaseURL: 'https://coogen-9b081-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coogen-9b081.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbOqeV1o8fMLHJlavi2R1XeVsykEQNYWs',
    appId: '1:977443506924:ios:21854f08d4bd3d0eff33c9',
    messagingSenderId: '977443506924',
    projectId: 'coogen-9b081',
    databaseURL: 'https://coogen-9b081-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coogen-9b081.appspot.com',
    iosClientId: '977443506924-rdbsi9s3ac9asptdcjb19jucb923j342.apps.googleusercontent.com',
    iosBundleId: 'com.example.immocrowd',
  );
}
